Wed, 07 Nov 2018 17:08:01 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/business/auth_user/user_service.py", line 29, in get_user
    user=User.objects.get(id=userid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 08 Nov 2018 10:02:34 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/business/auth_user/user_service.py", line 29, in get_user
    user=User.objects.get(id=userid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 08 Nov 2018 10:02:42 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/business/auth_user/user_service.py", line 29, in get_user
    user=User.objects.get(id=userid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 08 Nov 2018 10:03:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:03:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:03:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:03:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:03:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:03:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:03:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:03:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:03:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:03:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:03:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:03:36 simplelogger.py[line:28] ERROR [Errno 2] No such file or directory: '/web/www/teamcat/doraemon/static/project/contents/commit_testing_emailtemplate.html'
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/business/project/fortesting_service.py", line 231, in fortesting_commit
    ForTestingService.send_notification_email(fortesting.id, build_summary, email_template)
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/business/project/fortesting_service.py", line 353, in send_notification_email
    email_message = ForTestingService.create_email_message(fortesting, summary_info, email_tempalte_path)
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/business/project/fortesting_service.py", line 362, in create_email_message
    result = ForTestingService.create_commit_message(fortesting, summary_info, email_template_path)
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/business/project/fortesting_service.py", line 374, in create_commit_message
    email_templates = open(email_template_path, 'rb').read().decode()
FileNotFoundError: [Errno 2] No such file or directory: '/web/www/teamcat/doraemon/static/project/contents/commit_testing_emailtemplate.html'
Thu, 08 Nov 2018 10:04:41 simplelogger.py[line:28] ERROR ProjectModule matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 470, in get
    result=super(ModuleManager,self).get_queryset().get(id=moduleid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: ProjectModule matching query does not exist.
Thu, 08 Nov 2018 10:04:41 simplelogger.py[line:28] ERROR ProjectCodeUrl matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 128, in get
    result=super(CodeUrlManager,self).get_queryset().get(id=code_url_id)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: ProjectCodeUrl matching query does not exist.
Thu, 08 Nov 2018 10:04:43 simplelogger.py[line:18] ERROR (535, b'Error: authentication failed')
Thu, 08 Nov 2018 10:04:43 simplelogger.py[line:18] ERROR (535, b'Error: authentication failed')
Thu, 08 Nov 2018 10:04:43 simplelogger.py[line:18] ERROR (535, b'Error: authentication failed')
Thu, 08 Nov 2018 10:04:43 simplelogger.py[line:18] ERROR (535, b'Error: authentication failed')
Thu, 08 Nov 2018 10:04:43 simplelogger.py[line:18] ERROR (535, b'Error: authentication failed')
Thu, 08 Nov 2018 10:24:26 simplelogger.py[line:28] ERROR ProjectModule matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 470, in get
    result=super(ModuleManager,self).get_queryset().get(id=moduleid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: ProjectModule matching query does not exist.
Thu, 08 Nov 2018 10:24:26 simplelogger.py[line:28] ERROR ProjectCodeUrl matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 128, in get
    result=super(CodeUrlManager,self).get_queryset().get(id=code_url_id)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: ProjectCodeUrl matching query does not exist.
Thu, 08 Nov 2018 10:51:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:51:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:51:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:51:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:51:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:51:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:51:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:51:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:51:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:51:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 08 Nov 2018 10:51:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/teamcat_web/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
